### ISSUE TITLE
Failed to create window

### ISSUE THREAD

**Issue by K-Young96** [Cjmmmmmm/3D_PointCloud_Tracking#2]
GLFW Error: GLX: Forward compatibility requested but GLX_ARB_create_context_profile is unavailable
Failed to create window

Traceback (most recent call last):
  File "main.py", line 473, in <module>
    vis = visual_option()
  File "main.py", line 442, in visual_option
    opt.background_color = np.asarray([0, 0, 0])
AttributeError: 'NoneType' object has no attribute 'background_color'

**Comment by kylin0538** [comment]
me too
