### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 3: invalid start byte

### ISSUE THREAD

**Issue by K-Young96** [Cjmmmmmm/3D_PointCloud_Tracking#3]
I use my lidar data , but has an error : 
Traceback (most recent call last):
  File "main.py", line 486, in <module>
    multiple_replace(seq_file)
  File "main.py", line 413, in multiple_replace
    text = f.readlines()
  File "/home/kyoung/miniconda2/envs/AB3DMOT2/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 3: invalid start byte

**Comment by K-Young96** [comment]
your data is 128 lines,but mine is 16 lines .
