### ISSUE TITLE
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by K-Young96** [Cjmmmmmm/3D_PointCloud_Tracking#4]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by K-Young96** [comment]
Traceback (most recent call last):
  File "main.py", line 492, in <module>
    trackers = load_Kalman(seq_dets,total_frames,total_time)
  File "main.py", line 451, in load_Kalman
    dets = seq_dets[:, 8:15]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
